---
title: "Cars"
author: "Raniere Silva"
date: "11 September 2017"
output:
  # pdf_document:
  #  pandoc_args: [
  #    "--data-dir", "_pandoc",
  #    "--template", "apa6.tex",
  #    "--output", "apa6.pdf",
  #    # To solve
  #    #
  #    #     LaTeX Error: Environment Shaded undefined.
  #    #
  #    # and
  #    #
  #    #     LaTeX Error: Environment Highlighting undefined.
  #    #
  #    # the next argument is required
  #    "--listings"
  #  ]
  html_document:
    template: "university-of-manchester.html"
    pandoc_args: [
      "--data-dir", "_pandoc",
    ]
---

The car dataset gives the speed of cars and the distances taken to stop. **Note that the data were recorded in the 1920s.**

```{r}
knitr::kable(summary(cars))
```

You can also embed plots, for example:

```{r echo=FALSE}
plot(cars, xlab = "Speed (mph)", ylab = "Stopping distance (ft)",
     las = 1)
lines(lowess(cars$speed, cars$dist, f = 2/3, iter = 3), col = "red")
title(main = "cars data")
```

But you should also try the logarithmic scles.

```{r echo=FALSE}
plot(cars, xlab = "Speed (mph)", ylab = "Stopping distance (ft)",
     las = 1, log = "xy")
title(main = "cars data (logarithmic scales)")
```
